#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cups-bjnp
Version  : 2.0.3
Release  : 1
URL      : https://sourceforge.net/projects/cups-bjnp/files/cups-bjnp/2.0.3/cups-bjnp-2.0.3.tar.gz
Source0  : https://sourceforge.net/projects/cups-bjnp/files/cups-bjnp/2.0.3/cups-bjnp-2.0.3.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: cups-bjnp-license = %{version}-%{release}
BuildRequires : cups-dev

%description
This package contains a backend for CUPS for Canon printers using the 
proprietary BJNP network protocol.

%package license
Summary: license components for the cups-bjnp package.
Group: Default

%description license
license components for the cups-bjnp package.


%prep
%setup -q -n cups-bjnp-2.0.3
cd %{_builddir}/cups-bjnp-2.0.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583013913
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1583013913
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/cups-bjnp
cp %{_builddir}/cups-bjnp-2.0.3/COPYING %{buildroot}/usr/share/package-licenses/cups-bjnp/dfac199a7539a404407098a2541b9482279f690d
%make_install

%files
%defattr(-,root,root,-)
/usr/lib/cups/backend/bjnp

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cups-bjnp/dfac199a7539a404407098a2541b9482279f690d
